name: Synapse workspace deployment
on:
  workflow_dispatch
  
jobs:
  deploy_uat:
    environment: practice-rnd-uat
    name: Deploy to UAT Synapse WS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workspace_publish
        uses: actions/checkout@v2
        with:
          ref: workspace_publish
        
      - name: Deploy workspace to synapse
        uses: Azure/Synapse-workspace-deployment@V1.7.0
        with:
          TargetWorkspaceName: 'practicernd-synapse-uat'
          TemplateFile: './practice-rnd-synapse/TemplateForWorkspace.json'
          ParametersFile: './practice-rnd-synapse/TemplateParametersForWorkspace.json'
          environment: 'Azure Public'
          resourceGroup: 'pratice-rnd-uat'
          clientId: ${{ secrets.CLIENTID }}
          clientSecret: ${{ secrets.CLIENTSECRET }}
          subscriptionId: ${{ secrets.SUBID }}
          tenantId: ${{ secrets.TENANTID }}
          operation: 'deploy'
