name: Synapse workspace deployment
on:
  workflow_dispatch
  uses: Azure/Synapse-workspace-deployment@V1.7.0
  with:
    # Provide the Synapse workspace name where you want to deploy the artifacts.
    TargetWorkspaceName: practicernd-synapse-uat
    # Specify the path to the workspace artifacts template.
    TemplateFile: ./practice-rnd-synapse/TemplateForWorkspace.json.json
    # Specify the path to the template parameter file.
    ParametersFile: ./practice-rnd-synapse/TemplateParametersForWorkspace.json
    # Specify deployment parameter values.
    OverrideArmParameters: # optional, default is 
    # Provide the type of cloud environment. Valid values are: Azure Public, Azure China, Azure US Government, Azure Germany
    Environment: Azure Public
    # Provide the resource group of the target Synapse workspace.
    resourceGroup: practice-rnd-uat
    # Provide client id of service principal.
    clientId: # optional
    # Provide client secret of the service principal.
    clientSecret: # optional
    # Provide subscription id.
    subscriptionId: 1c873e20-f4f5-403d-b9e2-093a2df14944
    # Provide tenant id.
    tenantId: # optional
    # Delete the artifacts which are in the workspace but not in the template.
    DeleteArtifactsNotInTemplate: # optional
    # Use managed identity to generate the bearer token?
    managedIdentity: # optional
    # Deploy managed private endpoints in the template.
    deployManagedPrivateEndpoint: # optional
    # Mark the pipeline as failed if ARM overrides are missing.
    FailOnMissingOverrides: # optional
    # Provide path to the root folder.
    ArtifactsFolder: # optional
    # Provide name of the operation.
    operation: 'deploy'
    # Source for the npm package. Only for dev testing.
    npmpackage: # optional
